### PR TITLE
Added filters to punchcard view

### PR DESCRIPTION
**Pull request by kzhen**
I've added project and environment filters to the punch card (frequency) view. This allows you to start seeing some patterns, e.g. when was the last time we deployed to the "production' environment on a Friday?"

### CODE REVIEW

**Comment by merbla** [comment]
Love it! Thanks @kzhen.  I will have to setup some dev branch structure as I need to get the 6.3 version out.  Do you need this change on SplunkBase soon?

**Comment by merbla** [comment]
@kzhen I have spun up a few more branches and made you a contributor.  I have also made dev-6.2 the default branch.  I have to work out how to have 6.2 & 6.3 dev side by side.

**Comment by kzhen** [comment]
I don't need it up on SplunkBase anytime soon, I've modified the app running on our Splunk instance.

**Comment by kzhen** [comment]
Cool :) I might submit a few other tweaks as we start using it

**Pull request merged**
